---
version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - n 16
      - npm install
      - npm install -g @angular/cli

  pre_build:
    on-failure: ABORT
    commands:
      - echo Start pre_build...
      - node --version
      
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - npm run preBuild && ng build
      
  post_build:
    on-failure: ABORT
    commands:
      - echo Start post_build...
      - echo Build completed on `date`
      

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/aws-skills-mapping'
