---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    on-failure: ABORT
    commands:
      - echo Start pre_build...
      - node --version
      - npm install -g @angular/cli@14.0.2
      
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - ng build
      
  post_build:
    on-failure: ABORT
    commands:
      - echo Start post_build...
      

